microphone_analyzer:
  sample_rate: 48000
  chunk_size: 1024
  num_channels: 2
  fft_size: 1024
  energy_threshold: 500
  min_speech_duration: 0.5
  silence_duration_sec: 2.0
  buffer_max_sec: 30
  audio_topic: "/audio/raw_andrea"

vad_stt:
  input_sample_rate: 48000
  vad_sample_rate: 16000
  frame_ms: 30
  vad_mode: 2
  prebuffer_seconds: 1.0
  hang_in_ms: 50
  hang_out_ms: 200
  min_speech_ms: 200
  merge_gap_ms: 300
  num_channels: 1
  recordings_path: recordings
  audio_topic: '/audio/raw_andrea'
